---
title: "First Knit"
author: "Andrew Arredondo"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I went to Rosamond high school and yes I did graduate I just graduated in July. English and math are two complete different subjects but you need both in life I say the math teachers are more fun in math than in english. Math was easier to me because of how helping the teacher was when I had a question.The subject I did best in was econ in my opinion.
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
   I haven't purchased my computer yet I will this week. I would say I am a 5-6 I know a decent amount about laptops but still would be lost on some things.My internet connection is  6-7 depending how windy or hot it is during the day.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  I want to be called by my first name which is Andrew. Another name people could call me is Drew which is short for Andrew.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   What I want to achieve in life is to be look where i'm at and be happy with myself. I think econ would be the best subject for me, and I am trying to get a business degree.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I use to live in a foreign country, the country was Mexico I lived there for about two years when I was younger.I also want to visit Brazil or Greece and I have never been in the military if I were to I would pick the Navy, I would pick the Navy because I heard they are the branch that cares most about eduaction. 
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  I'm taking math 115 and no I did not know that about the difference between math 115 and 116. The grade I need to attain in stats to not upset my future plans would be a B or higher. My plan is to get my associate degree with A's and B's then transfer to a university.
   
 






  




